tasks:
  protoc:
    action: !protoc
      protoDir: ${module.rootDir}/src/proto
      javaDir: ${taskOutputDir}/java
      kotlinDir: ${taskOutputDir}/kotlin
      target: ${pluginSettings.target}
      version: ${pluginSettings.version}

generated:
  sources:
    - language: java
      directory: ${tasks.protoc.action.javaDir}
    - language: kotlin
      directory: ${tasks.protoc.action.kotlinDir}
